# Generated by Django 5.1.7 on 2025-03-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('registro_ans', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('ddd', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco_eletronico', models.EmailField(blank=True, max_length=255, null=True)),
                ('representante', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo_representante', models.CharField(blank=True, max_length=100, null=True)),
                ('regiao_de_comercializacao', models.IntegerField()),
                ('data_registro_ans', models.DateField()),
            ],
        ),
    ]
